### ISSUE TITLE
Ext distribution 

### ISSUE THREAD

**Issue by feamsr00** [isral/elastic_tabstops_mono.vsce#3]
Hi there hello!

I wonder if I could ask you if you won't mind publishing this awesome ext over at https://open-vsx.org/ too.

This would increase the reach of this awesome ext. To people using VSCodium for example.

Some publishing details https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by isral** [comment]
I'm sorry.
If you really need it, just publish it yourself.

**Comment by feamsr00** [comment]
Happy new year!

This has been completed. 

I hope you find this acceptable. Please let me know if you want anything on this page updated. It mirrors this repo exactly*. The build is not automated (yet), but attempts will be made to keep it manually updated as you update this repository.

https://open-vsx.org/extension/ONXGroup/elastic-tabstops-mono

*Except with the change of the publisher name. It wouldn't have been appropriate for me to create *your name\namespace* (isral) on a new platform, right? Regardless, I left all links alone.
